#ifndef BHARAT_PIXEL_FORMAT_H
#define BHARAT_PIXEL_FORMAT_H

typedef enum {
    PIXEL_FORMAT_UNKNOWN = 0,
    PIXEL_FORMAT_XRGB8888,
    PIXEL_FORMAT_ARGB8888,
    PIXEL_FORMAT_RGB565,
    PIXEL_FORMAT_BGRX8888,
    PIXEL_FORMAT_MONO_8
} pixel_format_t;

#endif // BHARAT_PIXEL_FORMAT_H
