#!/usr/bin/env python3
"""Bharat-OS Status and Component Maturity Generator.

Reads the components.yaml manifest and updates the status tables in README.md
and docs/dev/current-code-status.md automatically.
"""

import os
import yaml
from pathlib import Path

# Mapping of maturity levels to visual colored tags
MATURITY_BADGES = {
    "baseline": "🟢 **BASELINE**",
    "partial": "🟡 **PARTIAL**",
    "scaffold": "⚪ **SCAFFOLD**",
    "target": "🔵 **TARGET**",
}

def generate_markdown_table(components):
    lines = []
    lines.append("| Component Name | Maturity Level | Evidence / Verification Path | Key Blockers / Remarks |")
    lines.append("|---|---|---|---|")

    for comp_id, info in components.items():
        name = info.get("name", comp_id)
        maturity = info.get("maturity", "target").lower()
        badge = MATURITY_BADGES.get(maturity, f"**{maturity.upper()}**")
        evidence = info.get("evidence", "N/A")
        blockers = ", ".join(info.get("blockers", [])) if info.get("blockers") else "None"

        lines.append(f"| {name} | {badge} | `{evidence}` | {blockers} |")

    return "\n".join(lines)

def update_file_with_table(filepath, table_content):
    if not os.path.exists(filepath):
        print(f"Warning: File {filepath} does not exist.")
        return False

    content = Path(filepath).read_text(encoding="utf-8")

    start_marker = "<!-- START MATURITY TABLE -->"
    end_marker = "<!-- END MATURITY TABLE -->"

    if start_marker not in content or end_marker not in content:
        print(f"Warning: Markers not found in {filepath}. Skipping table insertion.")
        return False

    pattern = content.split(start_marker)
    prefix = pattern[0]
    suffix = pattern[1].split(end_marker)[1]

    new_content = f"{prefix}{start_marker}\n\n{table_content}\n\n{end_marker}{suffix}"
    Path(filepath).write_text(new_content, encoding="utf-8")
    print(f"Successfully updated status table in {filepath}")
    return True

def main():
    repo_root = Path(__file__).resolve().parents[2]
    manifest_path = repo_root / "delivery/status/components.yaml"

    if not manifest_path.exists():
        print(f"Error: Manifest '{manifest_path}' not found.")
        return

    with open(manifest_path, "r") as f:
        data = yaml.safe_load(f)

    components = data.get("components", {})
    table_content = generate_markdown_table(components)

    # 1. Update README.md
    readme_path = repo_root / "README.md"
    update_file_with_table(readme_path, table_content)

    # 2. Update/Write docs/dev/current-code-status.md
    status_doc_path = repo_root / "docs/dev/current-code-status.md"
    os.makedirs(status_doc_path.parent, exist_ok=True)

    doc_header = """# Bharat-OS Current Code Status & Components Maturity

This document is automatically generated from the canonical components manifest at `delivery/status/components.yaml`. Do not edit this file manually.

## Component Maturity Table

<!-- START MATURITY TABLE -->
<!-- END MATURITY TABLE -->
"""
    # Write default header if file does not exist or lacks markers
    if not status_doc_path.exists():
        status_doc_path.write_text(doc_header, encoding="utf-8")
    else:
        content = status_doc_path.read_text(encoding="utf-8")
        if "<!-- START MATURITY TABLE -->" not in content:
            status_doc_path.write_text(doc_header, encoding="utf-8")

    update_file_with_table(status_doc_path, table_content)

if __name__ == "__main__":
    main()
