#ifndef BHARAT_OS_HAL_SECURE_BOOT_H
#define BHARAT_OS_HAL_SECURE_BOOT_H

#include "secure_boot.h"
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

/**
 * HAL/Board interface for Secure Boot.
 * Allows each architecture and board to provide specialized policy discovery
 * and architecture-specific hardware security checks (e.g., TrustZone, PMP,
 * SGX).
 */

/**
 * Boards must implement this to provide the active boot policy.
 * If not implemented by a board, a default generic policy may be used.
 */
const bharat_boot_policy_t *hal_board_get_boot_policy(void);

/**
 * Architecture-specific hardware security check.
 * Called during early boot to verify that the specified policy can be enforced
 * by the current CPU/SoC features.
 */
int hal_secure_boot_arch_check(const bharat_boot_policy_t *policy);


// NEW BHARAT MULTIKERNEL TRUST EVIDENCE AND POLICY TOGGLES

typedef enum {
    BHARAT_TRUST_UNKNOWN = 0,
    BHARAT_TRUST_UNSIGNED,
    BHARAT_TRUST_MEASURED,
    BHARAT_TRUST_VERIFIED
} bharat_boot_trust_state_t;

typedef struct {
    bharat_boot_trust_state_t trust_state;
    uint32_t verified_stages_bitmap;
    uint8_t measurements_digest[32]; // Basic SHA-256 placeholder
    uint32_t policy_decision_record;
} bharat_trust_evidence_t;

typedef struct {
    bool smp_allowed;
    bool strict_secure_boot_required;
    bool unsigned_module_loading_disabled;
    bool panic_policy_strict;
    bool timer_preference_oneshot;
} bharat_profile_toggles_t;

typedef struct {
    bharat_boot_stage_t stage;
    uint8_t digest[64];
    uint32_t digest_len;
} bharat_boot_measurement_t;

typedef struct {
    uint64_t base;
    uint64_t size;
    uint32_t flags;
} bharat_secure_region_t;

typedef struct {
    uint64_t mmio_base;
    uint64_t mmio_size;
    uint64_t dma_base;
    uint64_t dma_size;
    uint32_t flags;
} bharat_crypto_dma_window_t;

/* Secure region flags */
#define BHARAT_SECURE_REGION_EXEC_NEVER (1U << 0)
#define BHARAT_SECURE_REGION_DEVICE_ONLY (1U << 1)
#define BHARAT_SECURE_REGION_ZERO_ON_RELEASE (1U << 2)
#define BHARAT_SECURE_REGION_ENCLAVE_ONLY (1U << 3)

/* Crypto DMA window flags */
#define BHARAT_CRYPTO_DMA_ENCRYPTED (1U << 0)
#define BHARAT_CRYPTO_DMA_INTEGRITY_PROTECTED (1U << 1)
#define BHARAT_CRYPTO_DMA_NO_CPU_ALIAS (1U << 2)

/*
 * Pull measurements generated by firmware/bootloader. Return 0 on success.
 * Implementations should update *inout_count to the actual number of entries
 * written to out_measurements.
 */
int hal_secure_boot_get_measurements(bharat_boot_measurement_t *out_measurements,
                                     size_t *inout_count);

/*
 * Verify measurements against the hardware root of trust and populate a
 * normalized trust evidence structure for later policy decisions.
 */
int hal_secure_boot_verify_measurements(
    const bharat_boot_measurement_t *measurements, size_t count,
    bharat_trust_evidence_t *out_evidence);

/*
 * Restrict/release a memory region so key material can be isolated from the
 * broader kernel/userspace address spaces.
 */
int hal_secure_mem_restrict_region(const bharat_secure_region_t *region);
int hal_secure_mem_release_region(const bharat_secure_region_t *region);

/*
 * Configure/tear-down a hardened MMIO + DMA aperture for crypto accelerators.
 */
int hal_secure_crypto_dma_window_config(const bharat_crypto_dma_window_t *window);
int hal_secure_crypto_dma_window_clear(const bharat_crypto_dma_window_t *window);

#endif // BHARAT_OS_HAL_SECURE_BOOT_H
