#ifndef BHARAT_UAPI_SYSCALL_NR_H_NEW
#define BHARAT_UAPI_SYSCALL_NR_H_NEW

#include <bharat/uapi/syscall/bh_syscall_numbers.h>

#ifdef __cplusplus
extern "C" {
#endif

#define BHARAT_SYSCALL_ABI_VERSION_MAJOR 1U
#define BHARAT_SYSCALL_ABI_VERSION_MINOR 0U
#define BHARAT_SYSCALL_ABI_FROZEN 1U

/* Numbering discipline: 0..255 core kernel ABI, 256..1023 reserved for future kernel ABI growth. */
#define BHARAT_SYSCALL_CORE_MIN 0U
#define BHARAT_SYSCALL_CORE_MAX 255U

typedef enum {
    SYSCALL_NOP = BH_SYS_NOP,
    SYSCALL_THREAD_CREATE = BH_SYS_THREAD_CREATE,
    SYSCALL_THREAD_DESTROY = BH_SYS_THREAD_DESTROY,
    SYSCALL_SCHED_YIELD = BH_SYS_SCHED_YIELD,
    SYSCALL_VMM_MAP_PAGE = BH_SYS_VMM_MAP_PAGE,
    SYSCALL_VMM_UNMAP_PAGE = BH_SYS_VMM_UNMAP_PAGE,
    SYSCALL_CAPABILITY_INVOKE = BH_SYS_CAPABILITY_INVOKE,
    SYSCALL_ENDPOINT_CREATE = BH_SYS_ENDPOINT_CREATE,
    SYSCALL_ENDPOINT_SEND = BH_SYS_ENDPOINT_SEND,
    SYSCALL_ENDPOINT_RECEIVE = BH_SYS_ENDPOINT_RECEIVE,
    SYSCALL_CAPABILITY_DELEGATE = BH_SYS_CAPABILITY_DELEGATE,
    SYSCALL_SCHED_SLEEP = BH_SYS_SCHED_SLEEP,
    SYSCALL_SCHED_SET_PRIORITY = BH_SYS_SCHED_SET_PRIORITY,
    SYSCALL_SCHED_SET_AFFINITY = BH_SYS_SCHED_SET_AFFINITY,
    SYSCALL_INTENT_SET = BH_SYS_INTENT_SET,
    SYSCALL_INTENT_GET = BH_SYS_INTENT_GET,
    SYSCALL_MEM_ALLOC_CLASS = BH_SYS_MEM_ALLOC_CLASS,
    SYSCALL_FAULT_DOMAIN_CREATE = BH_SYS_FAULT_DOMAIN_CREATE,
    SYSCALL_FAULT_DOMAIN_DESTROY = BH_SYS_FAULT_DOMAIN_DESTROY,
    SYSCALL_FAULT_DOMAIN_ATTACH = BH_SYS_FAULT_DOMAIN_ATTACH,
    SYSCALL_READ = BH_SYS_READ,
    SYSCALL_WRITE = BH_SYS_WRITE,
    SYSCALL_GET_SUBSYSTEM_CAPS = BH_SYS_GET_SUBSYSTEM_CAPS,
    SYSCALL_THREAD_EXIT = BH_SYS_THREAD_EXIT,
} syscall_id_t;

enum {
    SYSCALL_MAX = SYSCALL_THREAD_EXIT
};

#ifdef __cplusplus
}
#endif

#endif /* BHARAT_UAPI_SYSCALL_NR_H_NEW */
