#ifndef BH_PERSONALITY_VERSION_H
#define BH_PERSONALITY_VERSION_H

#define BH_PERSONALITY_ABI_VERSION_MAJOR 0
#define BH_PERSONALITY_ABI_VERSION_MINOR 1
#define BH_PERSONALITY_ABI_VERSION_PATCH 0

#endif // BH_PERSONALITY_VERSION_H
