#ifndef BHARAT_ARCH_X86_CPU_FEATURES_H
#define BHARAT_ARCH_X86_CPU_FEATURES_H

// Assume ARCH_CPU_FEAT_ARCH_BASE is already defined by arch_cpu_caps.h

typedef enum {
    ARCH_CPU_FEAT_X86_AVX = ARCH_CPU_FEAT_ARCH_BASE,
    ARCH_CPU_FEAT_X86_AVX2,
    ARCH_CPU_FEAT_X86_FMA,
    ARCH_CPU_FEAT_X86_PCID,
    ARCH_CPU_FEAT_X86_INVPCID,
    ARCH_CPU_FEAT_X86_FSGSBASE,
    ARCH_CPU_FEAT_X86_PCLMUL,
    ARCH_CPU_FEAT_X86_SHA,
    ARCH_CPU_FEAT_X86_AES,

    ARCH_CPU_FEAT_TARGET__COUNT
} arch_x86_cpu_feature_t;

#endif // BHARAT_ARCH_X86_CPU_FEATURES_H
