#ifndef BHARAT_ARCH_RISCV_CPU_FEATURES_H
#define BHARAT_ARCH_RISCV_CPU_FEATURES_H

// Assume ARCH_CPU_FEAT_ARCH_BASE is already defined by arch_cpu_caps.h

typedef enum {
    ARCH_CPU_FEAT_RISCV_ZBA = ARCH_CPU_FEAT_ARCH_BASE,
    ARCH_CPU_FEAT_RISCV_ZBB,
    ARCH_CPU_FEAT_RISCV_ZBC,
    ARCH_CPU_FEAT_RISCV_ZBS,
    ARCH_CPU_FEAT_RISCV_ZICBOM,
    ARCH_CPU_FEAT_RISCV_ZICBOZ,
    ARCH_CPU_FEAT_RISCV_V,

    ARCH_CPU_FEAT_TARGET__COUNT
} arch_riscv_cpu_feature_t;

#endif // BHARAT_ARCH_RISCV_CPU_FEATURES_H
