#ifndef BHARAT_UAPI_PERSONALITY_H
#define BHARAT_UAPI_PERSONALITY_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    BHARAT_PERSONALITY_NATIVE = 0,
    BHARAT_PERSONALITY_LINUX = 1,
    BHARAT_PERSONALITY_ANDROID = 2,
    BHARAT_PERSONALITY_WINDOWS = 3,
    BHARAT_PERSONALITY_POSIX_LITE = 4,
    BHARAT_PERSONALITY_AUTOMOTIVE = 5,
    BHARAT_PERSONALITY_ROBOTICS = 5,
    BHARAT_PERSONALITY_MAX = 31
} bharat_personality_id_t;

#ifdef __cplusplus
}
#endif

#endif // BHARAT_UAPI_PERSONALITY_H
