cmake_minimum_required(VERSION 3.20)
get_filename_component(repo "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)
include("${repo}/delivery/cmake/modules/BharatComponentPolicy.cmake")
set(BHARAT_PERSONALITY_PROFILE NATIVE)
set(BHARAT_TARGET_BOARD virt)
foreach(arch X86_64 ARM64 RISCV64 ARM32 RISCV32)
    set(BHARAT_ARCH_FAMILY "${arch}")
    foreach(profile EDGE DESKTOP RTOS AUTOMOTIVE_INFOTAINMENT)
        set(BHARAT_DEVICE_PROFILE "${profile}")
        foreach(gui ON OFF)
            foreach(option BHARAT_ENABLE_SERVICE_BOOT_DISPLAYD BHARAT_ENABLE_UI BHARAT_ENABLE_FBUI BHARAT_UI_LVGL)
                unset(${option} CACHE)
            endforeach()
            set(BHARAT_BOOT_GUI "${gui}" CACHE BOOL "" FORCE)
            bharat_apply_component_policy()
            if(profile STREQUAL "AUTOMOTIVE_INFOTAINMENT" OR gui)
                if(NOT BHARAT_ENABLE_SERVICE_BOOT_DISPLAYD)
                    message(FATAL_ERROR "Graphical/infotainment display daemon was removed")
                endif()
            elseif(BHARAT_ENABLE_SERVICE_BOOT_DISPLAYD OR BHARAT_ENABLE_UI OR BHARAT_ENABLE_FBUI)
                message(FATAL_ERROR "Headless ${arch}/${profile} selects graphical services")
            endif()
        endforeach()
    endforeach()
endforeach()
message(STATUS "PASS: headless policy and graphical/infotainment component preservation")
