# BharatIOPolicy.cmake
# Configures and validates Adaptive I/O Fabric compile-time settings for Bharat-OS

if(NOT DEFINED BHARAT_IO_PROFILE)
    if(ARCH STREQUAL "arm32" OR ARCH STREQUAL "riscv32")
        set(BHARAT_IO_PROFILE "TINY")
    elseif(BHARAT_DEVICE_PROFILE MATCHES "RTOS|DRONE|ROBOT|AUTOMOTIVE_ECU")
        set(BHARAT_IO_PROFILE "REALTIME")
    elseif(BHARAT_DEVICE_PROFILE MATCHES "EDGE|MOBILE|MEDICAL")
        set(BHARAT_IO_PROFILE "EMBEDDED")
    elseif(BHARAT_DEVICE_PROFILE MATCHES "DESKTOP|LAPTOP|AUTOMOTIVE_INFOTAINMENT")
        set(BHARAT_IO_PROFILE "BALANCED")
    elseif(BHARAT_DEVICE_PROFILE MATCHES "DATACENTER|NETWORK_APPLIANCE|CLOUD|SERVER")
        set(BHARAT_IO_PROFILE "THROUGHPUT")
    else()
        set(BHARAT_IO_PROFILE "BALANCED")
    endif()
endif()

set(BHARAT_IO_PROFILE "${BHARAT_IO_PROFILE}" CACHE STRING "Target storage I/O profile (TINY, EMBEDDED, BALANCED, THROUGHPUT, REALTIME)")
set_property(CACHE BHARAT_IO_PROFILE PROPERTY STRINGS TINY EMBEDDED BALANCED THROUGHPUT REALTIME)

if(BHARAT_IO_PROFILE STREQUAL "TINY")
    set(_async OFF)
    set(_batch OFF)
    set(_cache OFF)
    set(_direct ON)
    set(_polling OFF)
    set(_hybrid OFF)
    set(_zcopy OFF)
    set(_dynalloc OFF)
    set(_max_devices 2)
    set(_max_queues 1)
    set(_max_depth 4)
    set(_budget 32)
elseif(BHARAT_IO_PROFILE STREQUAL "EMBEDDED")
    set(_async ON)
    set(_batch OFF)
    set(_cache ON)
    set(_direct ON)
    set(_polling OFF)
    set(_hybrid OFF)
    set(_zcopy OFF)
    set(_dynalloc ON)
    set(_max_devices 4)
    set(_max_queues 2)
    set(_max_depth 32)
    set(_budget 256)
elseif(BHARAT_IO_PROFILE STREQUAL "BALANCED")
    set(_async ON)
    set(_batch ON)
    set(_cache ON)
    set(_direct ON)
    set(_polling ON)
    set(_hybrid ON)
    set(_zcopy ON)
    set(_dynalloc ON)
    set(_max_devices 8)
    set(_max_queues 4)
    set(_max_depth 128)
    set(_budget 2048)
elseif(BHARAT_IO_PROFILE STREQUAL "THROUGHPUT")
    set(_async ON)
    set(_batch ON)
    set(_cache ON)
    set(_direct ON)
    set(_polling ON)
    set(_hybrid ON)
    set(_zcopy ON)
    set(_dynalloc ON)
    set(_max_devices 16)
    set(_max_queues 16)
    set(_max_depth 1024)
    set(_budget 32768)
elseif(BHARAT_IO_PROFILE STREQUAL "REALTIME")
    set(_async ON)
    set(_batch ON)
    set(_cache OFF)
    set(_direct ON)
    set(_polling ON)
    set(_hybrid OFF)
    set(_zcopy ON)
    set(_dynalloc OFF)
    set(_max_devices 4)
    set(_max_queues 2)
    set(_max_depth 32)
    set(_budget 512)
endif()

option(BHARAT_IO_ENABLE_ASYNC "Enable asynchronous block queueing" ${_async})
option(BHARAT_IO_ENABLE_BATCH "Enable batch block submissions" ${_batch})
option(BHARAT_IO_ENABLE_CACHE_LAYER "Enable cache layer" ${_cache})
option(BHARAT_IO_ENABLE_DIRECT "Enable direct I/O path" ${_direct})
option(BHARAT_IO_ENABLE_POLLING "Enable polling completion mode" ${_polling})
option(BHARAT_IO_ENABLE_HYBRID_COMPLETION "Enable hybrid completion mode" ${_hybrid})
option(BHARAT_IO_ENABLE_ZERO_COPY "Enable zero-copy transfers" ${_zcopy})
option(BHARAT_IO_DYNAMIC_ALLOCATION "Enable runtime dynamic allocations" ${_dynalloc})

set(BHARAT_IO_MAX_DEVICES ${_max_devices} CACHE STRING "Maximum registered devices")
set(BHARAT_IO_MAX_QUEUES_PER_DEVICE ${_max_queues} CACHE STRING "Maximum queues per device")
set(BHARAT_IO_MAX_QUEUE_DEPTH ${_max_depth} CACHE STRING "Maximum queue depth")
set(BHARAT_IO_MEMORY_BUDGET_KB ${_budget} CACHE STRING "I/O memory budget in KB")

if(NOT DEFINED BHARAT_STORAGE_DRIVERS)
    if(BHARAT_IO_PROFILE STREQUAL "TINY")
        set(BHARAT_STORAGE_DRIVERS "memblk")
    elseif(BHARAT_IO_PROFILE STREQUAL "EMBEDDED")
        set(BHARAT_STORAGE_DRIVERS "sdhost;memblk")
    elseif(BHARAT_IO_PROFILE STREQUAL "BALANCED")
        set(BHARAT_STORAGE_DRIVERS "virtio_blk;memblk")
    elseif(BHARAT_IO_PROFILE STREQUAL "THROUGHPUT")
        set(BHARAT_STORAGE_DRIVERS "nvme;virtio_blk;memblk")
    elseif(BHARAT_IO_PROFILE STREQUAL "REALTIME")
        set(BHARAT_STORAGE_DRIVERS "sdhost;memblk")
    else()
        set(BHARAT_STORAGE_DRIVERS "memblk")
    endif()
endif()
set(BHARAT_STORAGE_DRIVERS "${BHARAT_STORAGE_DRIVERS}" CACHE STRING "Semicolon-separated list of enabled storage drivers")

# Initialize boolean options
set(BHARAT_ENABLE_DRIVER_MEMBLK OFF)
set(BHARAT_ENABLE_DRIVER_VIRTIO_BLK OFF)
set(BHARAT_ENABLE_DRIVER_NVME OFF)
set(BHARAT_ENABLE_DRIVER_SDHOST OFF)
set(BHARAT_ENABLE_DRIVER_AHCI OFF)

foreach(drv IN LISTS BHARAT_STORAGE_DRIVERS)
    if(drv STREQUAL "memblk")
        set(BHARAT_ENABLE_DRIVER_MEMBLK ON)
    elseif(drv STREQUAL "virtio_blk")
        set(BHARAT_ENABLE_DRIVER_VIRTIO_BLK ON)
    elseif(drv STREQUAL "nvme")
        set(BHARAT_ENABLE_DRIVER_NVME ON)
    elseif(drv STREQUAL "sdhost")
        set(BHARAT_ENABLE_DRIVER_SDHOST ON)
    elseif(drv STREQUAL "ahci")
        set(BHARAT_ENABLE_DRIVER_AHCI ON)
    else()
        message(WARNING "Unknown driver in BHARAT_STORAGE_DRIVERS: ${drv}")
    endif()
endforeach()

# Expose them as cache options for compatibility/overrides
set(BHARAT_ENABLE_DRIVER_MEMBLK ${BHARAT_ENABLE_DRIVER_MEMBLK} CACHE BOOL "Build memblk reference driver" FORCE)
set(BHARAT_ENABLE_DRIVER_VIRTIO_BLK ${BHARAT_ENABLE_DRIVER_VIRTIO_BLK} CACHE BOOL "Build virtio_blk driver" FORCE)
set(BHARAT_ENABLE_DRIVER_NVME ${BHARAT_ENABLE_DRIVER_NVME} CACHE BOOL "Build nvme driver" FORCE)
set(BHARAT_ENABLE_DRIVER_SDHOST ${BHARAT_ENABLE_DRIVER_SDHOST} CACHE BOOL "Build sdhost driver" FORCE)
set(BHARAT_ENABLE_DRIVER_AHCI ${BHARAT_ENABLE_DRIVER_AHCI} CACHE BOOL "Build ahci driver" FORCE)

# Compile-Time Policy Validation
if(BHARAT_IO_PROFILE STREQUAL "TINY" AND BHARAT_IO_MAX_QUEUES_PER_DEVICE GREATER 2)
    message(FATAL_ERROR "[IOPolicy] TINY profile does not support more than 2 queues per device (requested ${BHARAT_IO_MAX_QUEUES_PER_DEVICE})")
endif()

if(BHARAT_IO_PROFILE STREQUAL "REALTIME" AND BHARAT_IO_DYNAMIC_ALLOCATION)
    message(FATAL_ERROR "[IOPolicy] REALTIME profile prohibits dynamic allocation in fast paths")
endif()

if(BHARAT_IO_ENABLE_POLLING AND NOT BHARAT_ENABLE_DRIVER_MEMBLK AND NOT BHARAT_ENABLE_DRIVER_NVME)
    message(FATAL_ERROR "[IOPolicy] Polling requires at least one driver with poll support (memblk or nvme)")
endif()

if(BHARAT_IO_ENABLE_ZERO_COPY AND NOT BHARAT_ENABLE_DMA_MAP)
    message(FATAL_ERROR "[IOPolicy] Zero-copy requires BHARAT_ENABLE_DMA_MAP to be enabled")
endif()

# Resolve profile defines for configure_file
set(BHARAT_IO_PROFILE_TINY OFF)
set(BHARAT_IO_PROFILE_EMBEDDED OFF)
set(BHARAT_IO_PROFILE_BALANCED OFF)
set(BHARAT_IO_PROFILE_THROUGHPUT OFF)
set(BHARAT_IO_PROFILE_REALTIME OFF)

if(BHARAT_IO_PROFILE STREQUAL "TINY")
    set(BHARAT_IO_PROFILE_TINY ON)
elseif(BHARAT_IO_PROFILE STREQUAL "EMBEDDED")
    set(BHARAT_IO_PROFILE_EMBEDDED ON)
elseif(BHARAT_IO_PROFILE STREQUAL "BALANCED")
    set(BHARAT_IO_PROFILE_BALANCED ON)
elseif(BHARAT_IO_PROFILE STREQUAL "THROUGHPUT")
    set(BHARAT_IO_PROFILE_THROUGHPUT ON)
elseif(BHARAT_IO_PROFILE STREQUAL "REALTIME")
    set(BHARAT_IO_PROFILE_REALTIME ON)
endif()

set(BHARAT_IO_DRIVER_MEMBLK ${BHARAT_ENABLE_DRIVER_MEMBLK})
set(BHARAT_IO_DRIVER_VIRTIO_BLK ${BHARAT_ENABLE_DRIVER_VIRTIO_BLK})
set(BHARAT_IO_DRIVER_NVME ${BHARAT_ENABLE_DRIVER_NVME})
set(BHARAT_IO_DRIVER_SDHOST ${BHARAT_ENABLE_DRIVER_SDHOST})
set(BHARAT_IO_DRIVER_AHCI ${BHARAT_ENABLE_DRIVER_AHCI})

# Generate the config header
if(NOT DEFINED BHARAT_GEN_INCLUDE_DIR)
    set(BHARAT_GEN_INCLUDE_DIR "${CMAKE_BINARY_DIR}/generated/include")
endif()
file(MAKE_DIRECTORY "${BHARAT_GEN_INCLUDE_DIR}/bharat")

configure_file(
    "${CMAKE_SOURCE_DIR}/delivery/cmake/templates/io_config.h.in"
    "${BHARAT_GEN_INCLUDE_DIR}/bharat/io_config.h"
)

# Print the resolved policy
message(STATUS "--------------------------------------------------------")
message(STATUS "  [IOPolicy] Storage I/O Policy Resolved: ${BHARAT_IO_PROFILE}")
message(STATUS "  Async Submission: ${BHARAT_IO_ENABLE_ASYNC}")
message(STATUS "  Batch Submission: ${BHARAT_IO_ENABLE_BATCH}")
message(STATUS "  Cache Layer:      ${BHARAT_IO_ENABLE_CACHE_LAYER}")
message(STATUS "  Direct I/O:       ${BHARAT_IO_ENABLE_DIRECT}")
message(STATUS "  Polling:          ${BHARAT_IO_ENABLE_POLLING}")
message(STATUS "  Zero Copy:        ${BHARAT_IO_ENABLE_ZERO_COPY}")
message(STATUS "  Dynamic Alloc:    ${BHARAT_IO_DYNAMIC_ALLOCATION}")
message(STATUS "  Max Devices:      ${BHARAT_IO_MAX_DEVICES}")
message(STATUS "  Max Depth:        ${BHARAT_IO_MAX_QUEUE_DEPTH}")
message(STATUS "  Drivers:          ${BHARAT_STORAGE_DRIVERS}")
message(STATUS "--------------------------------------------------------")
