# BharatComponentPolicy.cmake
# Resolve and validate driver/service/subsystem selections from profile/personality/board.

function(bharat_component_option name default_value description)
    if(NOT DEFINED ${name})
        set(${name} ${default_value} CACHE BOOL "${description}")
    else()
        set(${name} ${${name}} CACHE BOOL "${description}" FORCE)
    endif()
endfunction()

function(bharat_require_component option_name reason)
    if(NOT ${option_name})
        message(FATAL_ERROR "${option_name}=OFF is invalid for this target: ${reason}")
    endif()
endfunction()

function(bharat_apply_component_policy)
    # Baseline defaults
    bharat_component_option(BHARAT_ENABLE_DRIVER_NET ON "Build networking drivers")
    bharat_component_option(BHARAT_ENABLE_DRIVER_ACCEL ON "Build accelerator drivers")
    bharat_component_option(BHARAT_ENABLE_DRIVER_CLUSTER_BUS ON "Build cluster bus drivers")
    bharat_component_option(BHARAT_ENABLE_DRIVER_AUTOMOTIVE_CAN OFF "Build automotive CAN driver")
    # Per-driver overrides (default to legacy group flags for compatibility)
    bharat_component_option(BHARAT_ENABLE_DRIVER_VIRTIO_NET ${BHARAT_ENABLE_DRIVER_NET} "Build virtio-net driver")
    bharat_component_option(BHARAT_ENABLE_DRIVER_PTP_CLOCK ${BHARAT_ENABLE_DRIVER_NET} "Build ptp-clock driver")
    bharat_component_option(BHARAT_ENABLE_DRIVER_FPGA_MGR ${BHARAT_ENABLE_DRIVER_ACCEL} "Build fpga manager driver")
    bharat_component_option(BHARAT_ENABLE_DRIVER_CAN_LOOPBACK ${BHARAT_ENABLE_DRIVER_AUTOMOTIVE_CAN} "Build CAN loopback driver")
    bharat_component_option(BHARAT_ENABLE_DRIVER_GENERIC_REGISTRY ON "Build generic driver registry")
    bharat_component_option(BHARAT_ENABLE_DRIVER_ARCH_IRQ_TIMER ON "Build arch IRQ/timer generic driver")
    bharat_component_option(BHARAT_ENABLE_DRIVER_BOARD_FABRIC ON "Build board fabric generic driver")

    bharat_component_option(BHARAT_ENABLE_SUBSYS_LINUX ON "Build Linux personality subsystem")
    bharat_component_option(BHARAT_ENABLE_SUBSYS_WINDOWS ON "Build Windows personality subsystem")
    bharat_component_option(BHARAT_ENABLE_SUBSYS_ANDROID OFF "Build Android personality subsystem")
    bharat_component_option(BHARAT_ENABLE_SUBSYS_AUTOMOTIVE OFF "Build automotive subsystem")

    bharat_component_option(BHARAT_ENABLE_SERVICE_BOOT_DISPLAYD ON "Build boot display daemon")
    bharat_component_option(BHARAT_ENABLE_SERVICE_NETWORK ON "Build network services")

    set(_profile "${BHARAT_DEVICE_PROFILE}")
    set(_personality "${BHARAT_PERSONALITY_PROFILE}")
    string(TOLOWER "${BHARAT_TARGET_BOARD}" _board)

    if(_profile STREQUAL "AUTOMOTIVE_ECU")
        set(BHARAT_ENABLE_DRIVER_AUTOMOTIVE_CAN ON CACHE BOOL "Build automotive CAN driver" FORCE)
        set(BHARAT_ENABLE_DRIVER_CAN_LOOPBACK ON CACHE BOOL "Build CAN loopback driver" FORCE)
        set(BHARAT_ENABLE_SUBSYS_AUTOMOTIVE ON CACHE BOOL "Build automotive subsystem" FORCE)
        set(BHARAT_ENABLE_SERVICE_NETWORK OFF CACHE BOOL "Build network services" FORCE)
        set(BHARAT_ENABLE_SERVICE_BOOT_DISPLAYD OFF CACHE BOOL "Build boot display daemon" FORCE)
    elseif(_profile STREQUAL "AUTOMOTIVE_INFOTAINMENT")
        set(BHARAT_ENABLE_DRIVER_AUTOMOTIVE_CAN ON CACHE BOOL "Build automotive CAN driver" FORCE)
        set(BHARAT_ENABLE_DRIVER_CAN_LOOPBACK ON CACHE BOOL "Build CAN loopback driver" FORCE)
        set(BHARAT_ENABLE_SUBSYS_AUTOMOTIVE ON CACHE BOOL "Build automotive subsystem" FORCE)
        set(BHARAT_ENABLE_SERVICE_NETWORK ON CACHE BOOL "Build network services" FORCE)
        set(BHARAT_ENABLE_SERVICE_BOOT_DISPLAYD ON CACHE BOOL "Build boot display daemon" FORCE)
        set(BHARAT_ENABLE_SUBSYS_ANDROID ON CACHE BOOL "Build Android personality subsystem" FORCE)
    endif()

    if(_board MATCHES "ecu")
        set(BHARAT_ENABLE_DRIVER_AUTOMOTIVE_CAN ON CACHE BOOL "Build automotive CAN driver" FORCE)
        set(BHARAT_ENABLE_DRIVER_CAN_LOOPBACK ON CACHE BOOL "Build CAN loopback driver" FORCE)
        set(BHARAT_ENABLE_SUBSYS_AUTOMOTIVE ON CACHE BOOL "Build automotive subsystem" FORCE)
    endif()

    if(_personality STREQUAL "LINUX")
        set(BHARAT_ENABLE_SUBSYS_LINUX ON CACHE BOOL "Build Linux personality subsystem" FORCE)
    elseif(_personality STREQUAL "WINDOWS")
        set(BHARAT_ENABLE_SUBSYS_WINDOWS ON CACHE BOOL "Build Windows personality subsystem" FORCE)
    elseif(_personality STREQUAL "MAC")
        # No dedicated subsystem target yet.
    elseif(_personality STREQUAL "NONE")
        # Keep defaults.
    else()
        message(FATAL_ERROR "Unsupported BHARAT_PERSONALITY_PROFILE='${BHARAT_PERSONALITY_PROFILE}'")
    endif()

    # Required component checks
    if(_profile STREQUAL "AUTOMOTIVE_ECU")
        bharat_require_component(BHARAT_ENABLE_DRIVER_AUTOMOTIVE_CAN "AUTOMOTIVE_ECU requires CAN driver")
        bharat_require_component(BHARAT_ENABLE_DRIVER_CAN_LOOPBACK "AUTOMOTIVE_ECU requires CAN loopback driver")
        bharat_require_component(BHARAT_ENABLE_SUBSYS_AUTOMOTIVE "AUTOMOTIVE_ECU requires automotive subsystem")
    elseif(_profile STREQUAL "AUTOMOTIVE_INFOTAINMENT")
        bharat_require_component(BHARAT_ENABLE_DRIVER_AUTOMOTIVE_CAN "AUTOMOTIVE_INFOTAINMENT requires CAN driver")
        bharat_require_component(BHARAT_ENABLE_DRIVER_CAN_LOOPBACK "AUTOMOTIVE_INFOTAINMENT requires CAN loopback driver")
        bharat_require_component(BHARAT_ENABLE_SUBSYS_AUTOMOTIVE "AUTOMOTIVE_INFOTAINMENT requires automotive subsystem")
        bharat_require_component(BHARAT_ENABLE_SERVICE_NETWORK "AUTOMOTIVE_INFOTAINMENT requires network services")
        bharat_require_component(BHARAT_ENABLE_SERVICE_BOOT_DISPLAYD "AUTOMOTIVE_INFOTAINMENT requires boot display")
    endif()

    if(_personality STREQUAL "LINUX")
        bharat_require_component(BHARAT_ENABLE_SUBSYS_LINUX "LINUX personality requires Linux subsystem")
    elseif(_personality STREQUAL "WINDOWS")
        bharat_require_component(BHARAT_ENABLE_SUBSYS_WINDOWS "WINDOWS personality requires Windows subsystem")
    endif()

    message(STATUS "Component policy resolved for profile=${BHARAT_DEVICE_PROFILE}, personality=${BHARAT_PERSONALITY_PROFILE}, board=${BHARAT_TARGET_BOARD}")
endfunction()
