function(bharat_set_arch_defaults)
    if(NOT DEFINED BHARAT_ARCH_FAMILY)
        if(CMAKE_SYSTEM_PROCESSOR MATCHES "riscv")
            set(BHARAT_ARCH_FAMILY "RISCV" CACHE STRING "Target architecture family" FORCE)
        elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "aarch64" OR CMAKE_SYSTEM_PROCESSOR MATCHES "arm")
            set(BHARAT_ARCH_FAMILY "ARM" CACHE STRING "Target architecture family" FORCE)
        else()
            set(BHARAT_ARCH_FAMILY "X86" CACHE STRING "Target architecture family" FORCE)
        endif()
    endif()

    if(NOT DEFINED BHARAT_ARCH_BITS)
        if(CMAKE_SYSTEM_PROCESSOR MATCHES "aarch64")
            set(BHARAT_ARCH_BITS "64" CACHE STRING "Target architecture bitness" FORCE)
        elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "^arm")
            set(BHARAT_ARCH_BITS "32" CACHE STRING "Target architecture bitness" FORCE)
        elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "64")
            set(BHARAT_ARCH_BITS "64" CACHE STRING "Target architecture bitness" FORCE)
        elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "32")
            set(BHARAT_ARCH_BITS "32" CACHE STRING "Target architecture bitness" FORCE)
        else()
            set(BHARAT_ARCH_BITS "64" CACHE STRING "Target architecture bitness" FORCE)
        endif()
    endif()

    if(NOT DEFINED BHARAT_ARCH_VARIANT)
        set(BHARAT_ARCH_VARIANT "GENERIC" CACHE STRING "Target architecture variant" FORCE)
    endif()

    if(BHARAT_ARCH_FAMILY STREQUAL "X86" AND BHARAT_ARCH_BITS STREQUAL "64")
        set(ARCH "x86_64" PARENT_SCOPE)
    elseif(BHARAT_ARCH_FAMILY STREQUAL "RISCV")
        if(BHARAT_ARCH_BITS STREQUAL "64")
            set(ARCH "riscv64" PARENT_SCOPE)
        else()
            set(ARCH "riscv32" PARENT_SCOPE)
        endif()
    elseif(BHARAT_ARCH_FAMILY STREQUAL "ARM")
        if(BHARAT_ARCH_BITS STREQUAL "64")
            set(ARCH "arm64" PARENT_SCOPE)
        else()
            set(ARCH "arm32" PARENT_SCOPE)
        endif()
    else()
        message(FATAL_ERROR "Unsupported architecture combination: family='${BHARAT_ARCH_FAMILY}' bits='${BHARAT_ARCH_BITS}'")
    endif()
endfunction()

function(bharat_set_profile_flag var_name expected actual)
    if("${actual}" STREQUAL "${expected}")
        set(${var_name} 1 PARENT_SCOPE)
    endif()
endfunction()
