name: Linux Host Tests (CI)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  host-build-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake ninja-build clang valgrind

      - name: Configure CMake (Host Test)
        run: cmake --preset host-test

      - name: Build Host Tests
        run: cmake --build --preset host-test

      - name: Run Host Tests
        run: ctest --preset host-test

      - name: Configure CMake (Sanitizers)
        run: cmake --preset host-test-asan

      - name: Build Host Tests (Sanitizers)
        run: cmake --build --preset host-test-asan

      - name: Run Host Tests (Sanitizers)
        run: ctest --preset host-test-asan

      - name: Configure CMake (Valgrind)
        run: cmake --preset host-test-valgrind

      - name: Build Host Tests (Valgrind)
        run: cmake --build --preset host-test-valgrind

      - name: Run Host Tests (Valgrind)
        run: ctest --preset host-test-valgrind -T memcheck
